zxing: Autospec creation for update from version 1.4.0 to version 2.0.0
Adrien Dorsaz (1):
      allow to optimize wasm build for any runtime environment

Alex Tran (1):
      Conditionally include iOS-Wrapper project (#415)

Bjørn Forsman (1):
      zxing.pc.in: fix when CMAKE_INSTALL_<dir> is absolute

Hendrik (1):
      Adding a wrapper for iOS (#337)

Hendrik von Prince (3):
      Change the bundle-identifier to make it AppStore-compatible
      Add some more DeocdeHints to the iOS-Wrapper
      Improve detection on iOS

Khoren Markosyan (1):
      README: add link to external Flutter wrapper (#356)

Markus Fisch (5):
      Include version number in result
      android: fix buffer size for strings from the JVM
      python: set UTF-8 when encoding barcodes
      Treat tab characters as text too
      Replace sprintf with snprintf

Paul Wise (1):
      Add options to the example reader/writers to show usage information and exit

Qingnan Duan (4):
      Enable PIC for Zueci in shared build
      Fix C4996 when compiled with MSVC (#381)
      Fix narrow_cast
      Fix typo in readme

TomZ (3):
      Avoid big-scary cmake warning for optional libs
      Make Qt6 based example actually work.
      Avoid mapping when not calling the bits() method

Uri Shabi (1):
      Update README.md

axxel (161):
      LogMatrix: don't crash when using uninitialized log
      DataMatrix: fix remaining issue in new c++20 multi-symbol detection
      [[deprecated]]: remove all deprecated API and code
      fuzzer: fix the usual unnoticed compile regressions
      Result: use utf8 by default (replace ZX_USE_UTF8 with ZX_USE_UTF16)
      Content: model GS1/AIM Application Indicator as flag instead of string
      example: compile with mandatory c++17 mode, prepare std::string_view usage
      DecodeHints: store `characterSet` as enum instead of string
      Error: store location info as std::string instead of string+int
      CharacterSet: use 1 instead of 4 bytes storage
      To/From-String: consistently take std::string_view and return std::string
      Error: save even more space by replacing std::string with char* + int
      ZXAlgorithm: fix includes
      Result: struct packing by member reordering
      c++: fix compile regression on (only) android (-1 can't be a char?!?)
      cmake: request c++17 also on client side cmake projects
      ZXAlgorithm: new general purpose ToString(int, len) helper
      README: add link to new iOS wrapper
      ZXAlgorithm: add missing include (fix build regression)
      README: put wrapper infos in separate REAME files
      README: fix links to local files
      DataBarExpanded: return standard conforming text instead of HRI
      c++17: use nested namespaces and other c++17 features in public API
      IWUY: remove unused includes
      ZXAlgorithms: Make ToString(val, len) perform a bounds check on the input
      ZXAlgorithms: use ToString(val, len) in 2 more places
      ZXAlgorithms: Introduce new `char ToDigit(int)` helper with bounds check
      c++: remove random c-style cast
      c++20: make VS be happy (unclear whether or not the standard requries this)
      VS: fix a type conversion warning (bool -> int)
      DataMatrix: tune multi-symbol mode
      MCDecoder: fix \n vs \r issue
      c++20: work around a bug in MSVC
      README: updated build instuctions, added links to binary sources
      Error: fix issue with Errors not reported (e.g. from QRReader)
      BitMatrix: Switch to binary output in SaveAsPBM
      test: improve readability of blackbox test output
      test: add missing codabar-2/04.txt
      test: update overlooked rssexpanded test stats
      Error: suppress Errors from MaxiCode reader as they are meaningless
      test: show unexpected detections in blackbox tests more prominently
      HybridBinarizer: ~10% performance gain in total matrix decoding time
      Range: cleanup/consolidate getRow and getPatternRow related code
      BitArray/BitMatrix: remove stale/unused API
      ZX_FAST_BIT_STORAGE: remove defunct packed bits variant of BitArray/Matrix
      BitMatrix: remove unparameterized set/unset functions
      example: add (hidden) performance measurement helper code in ZXingReader
      DataMatrix: improve detection rate in presence of noise
      ECI: remove unused `#include "TextDecoder.h"
      python: use new utf8 based `MultiFormatWriter::encode()` overload
      python: use pybind11 v2.10.0
      test: update to libfmt v9.0.0
      c++: fix remaining MSVC compiler warnings
      TextUtfEncoding: drop dependence of angleEscape feature on system locale
      TextUtfEncoding: attempted fix of build regression on win/macos
      TextUtfEncoding: replace Utf8Decode with slightly improved version
      TextUtfEncoding: use narrow_cast (instead of static cast)
      ECI: replace Qt originated charset conversion code with libzueci
      ECI: add support for UTF16/UTF32 in both BE and LE
      test: add full cycle text Encoder/Decoder tests
      TextUtfEncoding: code and API cleanup + new EscapeNonGraphical()
      test: fix deprecation warning
      cmake: attempt to fix `missing zueci.h` build regression
      cmake: fix build regression of non-BUILD_SHARED_LIBS config
      TextDecoder: add missing #include <stdexcept> (fix windows build #3)
      remove second copy of Apache license file
      cmake: use COMPATIBILITY SameMajorVersion in package version file
      test: trivial std::string_view improvement
      test: tune yet unused multi-symbol example set
      ContentTest: replace utf16 with utf8 usage
      Content: rename utf16() to utfW()
      HRI: add `HRIFromISO15434()` and rename GS1.* -> HRI.*
      TextUtfEncoding: use string_view as iteration device
      android: add ' ' after ':' in result text for better line breaks
      TextUtfEncodingTesttest: don't use wstring version of EscapeNonGraphical
      TextUtfEncoding: more type related code cosmetic
      TextUtfEncoding: deprecate this header and namespace altogether
      DecodeHintes: introduce `TextMode` to modify `Result::text` rendering
      QRCode: fix multi-symbol detection regression (fix #370)
      ZXingReader: improve performance measurement debugging code
      QRCode: remove std::acos in GenerateFinderPatternSets
      QRCode: increase upper limit of potentially detected symbols
      TextMode: fall back to `Plain` if `HRIFromGS1` returns empty string
      c++20: fix build regressions from u8"" and char8_t usage
      DataMatrix: fix #378
      Revert "c++20: fix build regressions from u8"" and char8_t usage"
      c++20: 2nd attempt to fix build regressions from u8"" and char8_t usage
      ci: add ASAN+UBSAN job and sanitizer support for unit tests
      ci: add missing quotes in new build-ubuntu-sanitize job
      Pattern: fix UB (applying non-zero offset to null pointer)
      HRI: use unicode "Control Pictures" for ASCII control characters
      README: mention limitations about writing MaxiCode and MQR
      DataBarExpanded: accept symbols with only AI 01 data (fix #384)
      update links and comments to refer to new zxing-cpp/zxing-cpp home
      test: print EscapeNonGraphical in log output
      ReadBarcode: ReadBarcode finally simply calls ReadBarcodes
      Inversion: implement new `DecodeHints::tryInvert` feature
      DecodeHints: compress struct size back to 12 bytes (from 16)
      android: fix layout issue with chips in landscape mode (copy'n'paste bug)
      Inversion: add `Result::isInverted` property
      Inversion: add `-noinvert` command line flag to ZXingReader
      ZXingReader: print either `Bytes` or `BytesECI` depending on `-mode`
      test: fix/workaround broken fuzzer compilation
      test: add unit test for GetPatternRow
      Aztec: reimplement AZDetector to support arbitrary symbol rotation/position
      test: disable test on MSVC that is supposed to fail but succeeds
      test: completely remove ill-advised/deprecated AZDetetor unit test
      algorithms: generalize FirstOrDefault() helper function
      Aztec: implement multi-symbol detection
      Aztec: improve resilience against asymmetric black/white thickness
      Result: improve operator== for linear symbologies (fix #399)
      Result: tune linear symbology duplication detection (fix #367)
      DecodeHints: set default `TextMode` from `Plain` to `HRI`
      ZXingReader: fix -pngout segfault with symbols near image boarder
      python: add `text_mode` parameter to `read_barcode`
      QRCode: transcode std::out_of_range to FormatError
      EscapeNonGraphical: use locale independent alternative to std::iswgraph
      c++: fix gcc compilation warning
      c++20: add missing include
      example: use proper `DecodeHints::setTryDownscale()` in ZXingReader
      Downscale: compare threshold against max instead of min of (width, height)
      QRDecoder: fix typo in error message
      QRDecoder: fix isMirrored detection (fix #428)
      QRDecoder: fix 1-bit error in second copy of FormatInfo in mirrored case
      QRFormatInformationTest: fix whitespace
      PDFDetector: fix #426 (PDF417 position issue)
      ODReader: fix issue with symbol merging when checkRows are involved
      ci: update python build tests to include python 3.11 (and drop 3.8)
      ci: update python build tests to include python 3.11 (and drop 3.8)
      AZDecoder: fix out of bounds access (#438)
      AZDetector: speed up processing of sample from #438 by 10x
      LogMatrix: minor performance improvement for fwrite
      Qt: Warn on invalid QVideoFrame content instead of throwing an exception
      Qt: check QVideoFrame->QImage conversion also in Qt5 (see last commit)
      android: work around limitations of c++-20 support in NDK
      android: update gradle, SDK version and a few dependencies
      MSVC bug: apply workaround independent of c++-version (amend 28ce8da)
      ECI: copy code of external libzueci project
      ECI: rename zueci.cpp to zueci.c to fix compilation regression with NDK
      Result: `int versionNumber()` -> `std::string version()`
      Aztec: return nbLayers as `Result::version()`
      Result: remove transition helper macro ZX_USE_UTF16
      Result: hide `text()` and `ecLevel()` implementation
      Result: hide 'internal use only' API from public class interface
      pkgConfig: move .pc file generation from top-level to library folder
      python: update pybind11 to 2.10.2
      test: update fmtlib to 9.1.0
      ZXConfig: remove unused #define ZX_HAVE_CONFIG
      cmake: harmonize cmake_minimum_required() calls to 3.14
      python: install module on "make install"
      AUTHORS: remove misleading/outdated author attribution
      cmake: fix warning about missing top-level project() statement
      Release: bump version from 1.4.0 -> 2.0.0, set SONAME to 3
      MultiFormatWriter: check for width*height overflow
      c++: remove unused `#include <clocale>`
      example: use move instead of copy constructor during vector<Result> merge
      test: disable ubsan on (Bit)Matrix constructors with manual check
      Result: two Results may very well be "equal" if their error contents match
      c++: silence unused variable compiler warning
      Code128: new decoding algorithm based on edge-2-edge patterns
      README.md: mention c++20 build option / impact

gitlost (5):
      PDFScanningDecoder::VerifyCodewordCount(): check codewords[0] exactly matches array size; add test
      PDFScanningDecoder: remove some unnecessary includes, sort
      ODDatabarReader::ConstructText(): strip GS1 Composite 2D linkage flag
      ODDataBarReader: comment typo
      MCDecode: allow for dodgy data in primary message, including postcode

th1722 (2):
      add missing #include <cmath> for std::abs
      c++20: add missing include (amend: dc2b28a)